#pragma once

#define типова_дефиниция typedef
#define използвайки using
#define имево_пространство namespace
#define върни return
#define ако if
#define иначе else
#define за for
#define докато while
#define прави do
#define нов new
#define изтрий delete
#define метни throw
#define хвърли throw
#define пробвай try
#define хвани catch

#define и and
#define или or
#define не not
#define ксор xor
#define е_равно_на ==
#define е_по_голямо_от >
#define е_по_голямо_или_равно_на >=
#define е_по_малко_от <
#define е_по_малко_или_равно_на <=
#define не_е_равно_на !=
#define е =
#define плюс +
#define притури +
#define плюс_равно +=
#define минус -
#define минус_равно -=
#define плюс_плюс ++
#define минус_минус --
#define вмъкване <<
#define побитово_изместване_наляво <<
#define побитово_изместване_наляво_равно <<=
#define извличане >>
#define побитово_изместване_надясно >>
#define побитово_изместване_надясно_равно >>=
#define побитово_и &
#define псевдоним &
#define адрес_на &
#define побитово_и_равно &=
#define побитово_или |
#define побитово_или_равно |=
#define побитово_не ~
#define побитово_не_равно ~=
#define по *
#define указател *
#define достъпи_стойността_на *
#define по_равно *=
#define наследява_от :
#define разрешаване_на_обхват ::

#define константен const
#define структура struct
#define клас class
#define шаблон template
#define приятел friend
#define публичен public
#define частен private
#define защитен protected
#define статичен static
#define виртуален virtual
#define масив(name, num) name[num]
#define дълъг long
#define къс short
#define беззнаков unsigned
#define знаков signed
#define низ string
#define целочислен_тип int
#define символ char
#define реален_тип float
#define двоен_реален_тип double
#define безтипов void
#define вярно true
#define грешно false
#define нулев_показател nullptr

#define този this
#define стандартен std
#define край_на_ред endl
